webtalk_init -webtalk_dir D:/wjj/Intelligent-Architecture/Lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov  3 15:00:15 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8be8bf13-30e0-41d0-a1aa-27a39de65a9a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "29707501af034d6797fc175e88f7b402" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700KF" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3610 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10841735 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "21.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17296_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2425677348 -regid "" -xml D:/wjj/Intelligent-Architecture/Lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/wjj/Intelligent-Architecture/Lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/wjj/Intelligent-Architecture/Lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
