# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.cache/wt [current_project]
set_property parent.project_path C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/user_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_1/bd_886d_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_2/bd_886d_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_3/bd_886d_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_4/bd_886d_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_5/bd_886d_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_6/bd_886d_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_7/bd_886d_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_8/bd_886d_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_9/bd_886d_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_10/bd_886d_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_11/bd_886d_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_12/bd_886d_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_13/bd_886d_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_14/bd_886d_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_15/bd_886d_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_16/bd_886d_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_20/bd_886d_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_21/bd_886d_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_22/bd_886d_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_23/bd_886d_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_24/bd_886d_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_25/bd_886d_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_26/bd_886d_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_27/bd_886d_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_28/bd_886d_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_29/bd_886d_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_30/bd_886d_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_31/bd_886d_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_33/bd_886d_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_34/bd_886d_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_35/bd_886d_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_36/bd_886d_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_37/bd_886d_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_38/bd_886d_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_40/bd_886d_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_41/bd_886d_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_42/bd_886d_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_43/bd_886d_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_44/bd_886d_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_45/bd_886d_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_47/bd_886d_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_48/bd_886d_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_49/bd_886d_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_50/bd_886d_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_51/bd_886d_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/bd_0/ip/ip_52/bd_886d_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_MM_TOP_0_0/design_1_MM_TOP_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_2/design_1_axi_bram_ctrl_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/design_1_axi_bram_ctrl_0_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_bram_0/design_1_axi_bram_ctrl_1_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_2_bram_0/design_1_axi_bram_ctrl_2_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_3_bram_0/design_1_axi_bram_ctrl_3_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/Architecture/Intelligent-Architecture/Lab5-Naive-TPU/lab5_proj/proj/PE.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
