# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/debug.xdc

# IP: ip/out_align_fifo/out_align_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==out_align_fifo || ORIG_REF_NAME==out_align_fifo} -quiet] -quiet

# IP: ip/BRAM_WM_128b/BRAM_WM_128b.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_WM_128b || ORIG_REF_NAME==BRAM_WM_128b} -quiet] -quiet

# IP: ip/BRAM_FM_64b/BRAM_FM_64b.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_FM_64b || ORIG_REF_NAME==BRAM_FM_64b} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MM_TOP_0_0/design_1_MM_TOP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_MM_TOP_0_0 || ORIG_REF_NAME==design_1_MM_TOP_0_0} -quiet] -quiet

# IP: ip/out_align_fifo/out_align_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==out_align_fifo || ORIG_REF_NAME==out_align_fifo} -quiet] -quiet

# IP: ip/BRAM_WM_128b/BRAM_WM_128b.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_WM_128b || ORIG_REF_NAME==BRAM_WM_128b} -quiet] -quiet

# IP: ip/BRAM_FM_64b/BRAM_FM_64b.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_FM_64b || ORIG_REF_NAME==BRAM_FM_64b} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_2/design_1_axi_bram_ctrl_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_2 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_0/design_1_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_bram_0/design_1_axi_bram_ctrl_1_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_bram_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_2_bram_0/design_1_axi_bram_ctrl_2_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_2_bram_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_2_bram_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_3_bram_0/design_1_axi_bram_ctrl_3_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_3_bram_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_3_bram_0} -quiet] -quiet

# XDC: ip/out_align_fifo/out_align_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==out_align_fifo || ORIG_REF_NAME==out_align_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/BRAM_WM_128b/BRAM_WM_128b_ooc.xdc

# XDC: ip/BRAM_FM_64b/BRAM_FM_64b_ooc.xdc

# XDC: ip/out_align_fifo/out_align_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==out_align_fifo || ORIG_REF_NAME==out_align_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/BRAM_WM_128b/BRAM_WM_128b_ooc.xdc

# XDC: ip/BRAM_FM_64b/BRAM_FM_64b_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
