webtalk_init -webtalk_dir E:/workspace/_Intelligent_Computing_Architectures2/lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 22 16:24:17 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0eb196d5-c817-470d-a4b3-fb360c1e17d8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c5a28d8a5ecf455a95c88ac34f77405c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "170945 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.55_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15340_KB" -context "xsim\\usage"
webtalk_transmit -clientid 530062632 -regid "" -xml E:/workspace/_Intelligent_Computing_Architectures2/lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/workspace/_Intelligent_Computing_Architectures2/lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/workspace/_Intelligent_Computing_Architectures2/lab3/proj/matmul.sim/sim_1/behav/xsim/xsim.dir/Multiply_8x8_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
